# Single kustomization.yaml with embedded resources and patches
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# Embedded resource definitions
# Define the Deployment
deployment.yaml: |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend-app
    template:
      metadata:
        labels:
          app: backend-app
      spec:
        containers:
        - name: backend-app
          image: nginx:1.17.1
          ports:
          - containerPort: 80

# Define the Service
service.yaml: |
  apiVersion: v1
  kind: Service
  metadata:
    name: my-service
  spec:
    type: ClusterIP
    selector:
      app: backend-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

# Patches to customize the resources
patchesStrategicMerge:
  - patch.yaml

# Embedded patch definition
patch.yaml: |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend-app
  spec:
    replicas: 1
