apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: backend-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-app
